{% set name = "rxn-utils" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rxn-utils-{{ version }}.tar.gz
  sha256: 5af2feabb4b82dffb2aa3dda6973c6d9f658175d36380ac36d8e88808afa033e

build:
  entry_points:
    - rxn-extract-csv-column = rxn.utilities.scripts.extract_csv_column:main
    - rxn-stable-shuffle = rxn.utilities.scripts.stable_shuffle:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=59.2.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.2.0
    - click >=8.0
    - diskcache >=5.2.1
    - pydantic >=1.9.0
    - pydantic-settings >=2.1.0
    - pymongo >=3.9.0
    - tqdm >=4.31.0
    - typing-extensions >=4.1.1

test:
  imports:
    - rxn
  commands:
    - pip check
    - rxn-extract-csv-column --help
    - rxn-stable-shuffle --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rxn4chemistry/rxn-utilities
  summary: General utilities (not related to chemistry)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
